[build]
  base = "frontend"
  publish = "frontend/build"
  command = "cd frontend && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-heroku-app.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200