[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-heroku-app.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 